### ISSUE TITLE
Invalid yaml when installing dsc v2.1.2

### ISSUE THREAD

**Issue by jonathanhoskin** [michaelklishin/cassandra-chef-cookbook#141]
After installing using the default recipe the cassandra service fails to start. Upon closer inspection of the logs, it is throwing an exception.

My attributes:

    default[:cassandra][:cluster_name] = 'ClusterName'
    default[:cassandra][:version] = '2.1.2'
    default[:cassandra][:package_name] = 'dsc21'
    default[:cassandra][:setup_jamm] = true

Error:

    Invalid yaml. Please remove properties [multithreaded_compaction, memtable_flush_queue_size, compaction_preheat_key_cache, in_memory_compaction_limit_in_mb] from your cassandra.yaml

Trace:

    ERROR [main] 2014-11-19 04:45:53,433 DatabaseDescriptor.java:138 - Fatal configuration error
    org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml. Please remove properties [multithreaded_compaction, memtable_flush_queue_size, compaction_preheat_key_cache, in_memory_compaction_limit_in_mb] from your cassandra.yaml
            at org.apache.cassandra.config.YamlConfigurationLoader$MissingPropertiesChecker.check(YamlConfigurationLoader.java:162) ~[apache-cassandra-2.1.2.jar:2.1.2]
            at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:115) ~[apache-cassandra-2.1.2.jar:2.1.2]
            at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:84) ~[apache-cassandra-2.1.2.jar:2.1.2]
            at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:158) ~[apache-cassandra-2.1.2.jar:2.1.2]
            at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:133) ~[apache-cassandra-2.1.2.jar:2.1.2]
            at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:96) [apache-cassandra-2.1.2.jar:2.1.2]
            at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:448) [apache-cassandra-2.1.2.jar:2.1.2]
            at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:537) [apache-cassandra-2.1.2.jar:2.1.2]

Any ideas?

**Comment by 13h3r** [comment]
is this fixed already?

**Comment by michaelklishin** [comment]
I'm closing this as old, please re-open if this is still relevant.
