### ISSUE TITLE
Cannot load GraphiteSender

### ISSUE THREAD

**Issue by adecarolis** [michaelklishin/cassandra-chef-cookbook#273]
Hi,
I can't manage to start with Metrics Reporter enabled. This happens with JDK 8 on Centos:

```
Exception (java.lang.NoClassDefFoundError) encountered during startup: com/codahale/metrics/graphite/GraphiteSender
java.lang.NoClassDefFoundError: com/codahale/metrics/graphite/GraphiteSender
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.getDeclaredConstructor(Class.java:2178)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.createEmptyJavaBean(Constructor.java:215)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:276)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:247)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:509)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
        at com.addthis.metrics.reporter.config.AbstractReporterConfig.loadFromFile(AbstractReporterConfig.java:41)
        at com.addthis.metrics3.reporter.config.ReporterConfig.loadFromFile(ReporterConfig.java:249)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:309)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:481)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:588)
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.graphite.GraphiteSender
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 24 more
ERROR 20:30:39 Exception encountered during startup
```

Alain

**Comment by michaelklishin** [comment]
The metrics (or metrics-graphite specifically) dependency isn't on classpath. I'm not sure if it should be, as I'd expect mandatory dependencies to ship with Cassandra.

**Comment by powellchristoph** [comment]
So how do we resolve this issue?

**Comment by waltari2001** [comment]
Having the same issue.

**Comment by powellchristoph** [comment]
I did some digging and found that this isn't a problem with the cookbook. The default metrics reporter `yammer/metrics/metrics-graphite/2.2.0/metrics-graphite-2.2.0.jar` does not support cassandra 2.2. I had to swap it out with the dropwizard metrics plugin and it works perfectly fine. 

Here are the attrs that I am over-writing in my wrapper cookbook.

```
default['cassandra']['metrics_reporter']['enabled'] = true
default['cassandra']['metrics_reporter']['name'] = 'metrics-graphite'
default['cassandra']['metrics_reporter']['jar_url'] = 'http://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-graphite/3.1.2/metrics-graphite-3.1.2.jar'
default['cassandra']['metrics_reporter']['sha256sum'] = 'b08f4fd5907c7fa5b4dacc047ce4c7bc9a2a18c3860e2b8e8b84a0149ef326e1'
default['cassandra']['metrics_reporter']['jar_name'] = 'metrics-graphite-3.1.2.jar'
```

**Comment by michaelklishin** [comment]
Thank you, @powellchristoph!

**Comment by waltari2001** [comment]
Thanks @powellchristoph

**Comment by bhisey** [comment]
What version of metrics reporter we shall be using for cassandra 3.11.1
