### ISSUE TITLE
Fix resource cloning deprecation for `apt-transport-https`

### ISSUE THREAD

**Issue by eyalzek** [michaelklishin/cassandra-chef-cookbook#351]
Getting the following deprecation message when using the cookbook:

```
Deprecated features used!
         Cloning resource attributes for apt_package[apt-transport-https] from prior resource
       Previous apt_package[apt-transport-https]: /tmp/kitchen/cache/cookbooks/cassandra-dse/recipes/repositories.rb:31:in `from_file'
       Current  apt_package[apt-transport-https]: /tmp/kitchen/cache/cookbooks/apt/recipes/default.rb:91:in `from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/resource_cloning.rb:58:in `emit_cloned_resource_warning'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
```

coming from this line:
https://github.com/michaelklishin/cassandra-chef-cookbook/blob/master/recipes/repositories.rb#L31

is this cookbook actually dependent of `apt`? most of the `apt` resources are available as part of the chef core starting version 12.9.1...
https://github.com/michaelklishin/cassandra-chef-cookbook/blob/master/metadata.rb#L12

**Comment by michaelklishin** [comment]
We can't require Chef 12.9.1 just yet.

**Comment by eyalzek** [comment]
What's preventing it atm?

**Comment by michaelklishin** [comment]
@eyalzek there are users who use older versions?

**Comment by eyalzek** [comment]
Yeah but that's not stopping most of the other cookbooks in the chef supermarket to upgrade. This change seems due since chef 13 is already out and will become the standard soon.
If someone wants to continue running an older version they should just use a version tag to apply a constraint and that's it...

**Comment by michaelklishin** [comment]
@eyalzek when "soon" happens, we can move to whatever's available in the core. A deprecation message is not a big deal.

Using older cookbook versions means they won't get any other improvements in master.

**Comment by michaelklishin** [comment]
@eyalzek I think now we can require 12.9 or even 13. Please submit a PR? Note that there are funky things going on with the specs, I'm investigating but not getting very far just yet.

**Comment by eyalzek** [comment]
Sorry, don't have much time for a complete adaptation - also, I'm not entirely sure what are the full changes this requires

**Comment by michaelklishin** [comment]
@eyalzek I did a bit of work on this and getting closer to requiring at least Chef 12.9.1. Unfortunately, some dependency cookbooks used by Test Kitchen and/or ChefSpec seem to need updating for Chef 13. I am not deeply familiar with any of them so it takes time to figure out what part is problematic and whether there were new versions we can use.

But I managed to get things moving towards requiring a recent Chef 12 version.

**Comment by michaelklishin** [comment]
@eyalzek with #365 and a bit of earlier work we are ready to consider more changes, potentially bumping the version to 5.0. Please feel free to send any PRs you had in mind :)
